<?   
class SearchLocationClient
{
	var $conn = null;
	function SearchLocationClient(){
		$this->conn = &ADONewConnection("mysql");  
		$this->conn->Connect(SQL_HOST,SQL_USER,SQL_PASSWORD,SQL_BDD);
	}
	
	function createSearchLocationClient($params){ 
		$this->conn->AutoExecute("vue_search_location_client", $params,"INSERT"); 
		return $this->conn->Insert_ID();				
	}
	
	function updateSearchLocationClient($params){
		extract($params,EXTR_OVERWRITE) ;
		$this->conn->AutoExecute("vue_search_location_client", $params, "UPDATE", "idvue_search_location_client = ".$idvue_search_location_client); 
	}
	
	function deleteSearchLocationClient($params){
		extract($params,EXTR_OVERWRITE) ;	
		$sql="DELETE FROM  vue_search_location_client WHERE idvue_search_location_client = $idvue_search_location_client"; 
		return $this->conn->Execute($sql); 	
	}
	
	function getOneSearchLocationClient($params){
		extract($params,EXTR_OVERWRITE) ;
		$all = (empty($all))? "*" : $all;	
		$sql="select ".$all." from vue_search_location_client where 1 " ;
			if(!empty($idlocation_client)){ $sql .= " AND idlocation_client ".sqlIn($idlocation_client) ; }
			if(!empty($noidlocation_client)){ $sql .= " AND idlocation_client ".sqlNotIn($noidlocation_client) ; }
			if(!empty($lt_idlocation_client)){ $sql .= " AND idlocation_client < '".$lt_idlocation_client."'" ; }
			if(!empty($gt_idlocation_client)){ $sql .= " AND idlocation_client > '".$gt_idlocation_client."'" ; }
			if(!empty($type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlIn($type_location_client_idtype_location_client) ; }
			if(!empty($notype_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlNotIn($notype_location_client_idtype_location_client) ; }
			if(!empty($lt_type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client < '".$lt_type_location_client_idtype_location_client."'" ; }
			if(!empty($gt_type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client > '".$gt_type_location_client_idtype_location_client."'" ; }
			if(!empty($client_idclient)){ $sql .= " AND client_idclient ".sqlIn($client_idclient) ; }
			if(!empty($noclient_idclient)){ $sql .= " AND client_idclient ".sqlNotIn($noclient_idclient) ; }
			if(!empty($lt_client_idclient)){ $sql .= " AND client_idclient < '".$lt_client_idclient."'" ; }
			if(!empty($gt_client_idclient)){ $sql .= " AND client_idclient > '".$gt_client_idclient."'" ; }
			if(!empty($numeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlIn($numeroLocation_client) ; }
			if(!empty($nonumeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlNotIn($nonumeroLocation_client) ; }
			if(!empty($lt_numeroLocation_client)){ $sql .= " AND numeroLocation_client < '".$lt_numeroLocation_client."'" ; }
			if(!empty($gt_numeroLocation_client)){ $sql .= " AND numeroLocation_client > '".$gt_numeroLocation_client."'" ; }
			if(!empty($dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlIn($dateCreationLocation_client) ; }
			if(!empty($nodateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlNotIn($nodateCreationLocation_client) ; }
			if(!empty($lt_dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client < '".$lt_dateCreationLocation_client."'" ; }
			if(!empty($gt_dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client > '".$gt_dateCreationLocation_client."'" ; }
			if(!empty($dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlIn($dateDebutLocation_client) ; }
			if(!empty($nodateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlNotIn($nodateDebutLocation_client) ; }
			if(!empty($lt_dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client < '".$lt_dateDebutLocation_client."'" ; }
			if(!empty($gt_dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client > '".$gt_dateDebutLocation_client."'" ; }
			if(!empty($dateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlIn($dateFinLocation_client) ; }
			if(!empty($nodateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlNotIn($nodateFinLocation_client) ; }
			if(!empty($lt_dateFinLocation_client)){ $sql .= " AND dateFinLocation_client < '".$lt_dateFinLocation_client."'" ; }
			if(!empty($gt_dateFinLocation_client)){ $sql .= " AND dateFinLocation_client > '".$gt_dateFinLocation_client."'" ; }
			if(!empty($dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlIn($dateClotureLocation_client) ; }
			if(!empty($nodateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlNotIn($nodateClotureLocation_client) ; }
			if(!empty($lt_dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client < '".$lt_dateClotureLocation_client."'" ; }
			if(!empty($gt_dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client > '".$gt_dateClotureLocation_client."'" ; }
			if(!empty($idligne_location_client)){ $sql .= " AND idligne_location_client ".sqlIn($idligne_location_client) ; }
			if(!empty($noidligne_location_client)){ $sql .= " AND idligne_location_client ".sqlNotIn($noidligne_location_client) ; }
			if(!empty($lt_idligne_location_client)){ $sql .= " AND idligne_location_client < '".$lt_idligne_location_client."'" ; }
			if(!empty($gt_idligne_location_client)){ $sql .= " AND idligne_location_client > '".$gt_idligne_location_client."'" ; }
			if(!empty($localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlIn($localisation_idlocalisation) ; }
			if(!empty($nolocalisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlNotIn($nolocalisation_idlocalisation) ; }
			if(!empty($lt_localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation < '".$lt_localisation_idlocalisation."'" ; }
			if(!empty($gt_localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation > '".$gt_localisation_idlocalisation."'" ; }
			if(!empty($materiel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlIn($materiel_idmateriel) ; }
			if(!empty($nomateriel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlNotIn($nomateriel_idmateriel) ; }
			if(!empty($lt_materiel_idmateriel)){ $sql .= " AND materiel_idmateriel < '".$lt_materiel_idmateriel."'" ; }
			if(!empty($gt_materiel_idmateriel)){ $sql .= " AND materiel_idmateriel > '".$gt_materiel_idmateriel."'" ; }
			if(!empty($location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlIn($location_client_idlocation_client) ; }
			if(!empty($nolocation_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlNotIn($nolocation_client_idlocation_client) ; }
			if(!empty($lt_location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client < '".$lt_location_client_idlocation_client."'" ; }
			if(!empty($gt_location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client > '".$gt_location_client_idlocation_client."'" ; }
			if(!empty($dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlIn($dateCreationLigne_location_client) ; }
			if(!empty($nodateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlNotIn($nodateCreationLigne_location_client) ; }
			if(!empty($lt_dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client < '".$lt_dateCreationLigne_location_client."'" ; }
			if(!empty($gt_dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client > '".$gt_dateCreationLigne_location_client."'" ; }
			if(!empty($dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlIn($dateDebutLigne_location_client) ; }
			if(!empty($nodateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlNotIn($nodateDebutLigne_location_client) ; }
			if(!empty($lt_dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client < '".$lt_dateDebutLigne_location_client."'" ; }
			if(!empty($gt_dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client > '".$gt_dateDebutLigne_location_client."'" ; }
			if(!empty($dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlIn($dateClotureLigne_location_client) ; }
			if(!empty($nodateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlNotIn($nodateClotureLigne_location_client) ; }
			if(!empty($lt_dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client < '".$lt_dateClotureLigne_location_client."'" ; }
			if(!empty($gt_dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client > '".$gt_dateClotureLigne_location_client."'" ; }
			if(!empty($dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlIn($dateFinLigne_location_client) ; }
			if(!empty($nodateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlNotIn($nodateFinLigne_location_client) ; }
			if(!empty($lt_dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client < '".$lt_dateFinLigne_location_client."'" ; }
			if(!empty($gt_dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client > '".$gt_dateFinLigne_location_client."'" ; }
			if(!empty($dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlIn($dureeLigne_location_client) ; }
			if(!empty($nodureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlNotIn($nodureeLigne_location_client) ; }
			if(!empty($lt_dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client < '".$lt_dureeLigne_location_client."'" ; }
			if(!empty($gt_dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client > '".$gt_dureeLigne_location_client."'" ; }
			if(!empty($uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlIn($uniteDureeLigne_location_client) ; }
			if(!empty($nouniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlNotIn($nouniteDureeLigne_location_client) ; }
			if(!empty($lt_uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client < '".$lt_uniteDureeLigne_location_client."'" ; }
			if(!empty($gt_uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client > '".$gt_uniteDureeLigne_location_client."'" ; }
			if(!empty($pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlIn($pvhtLigne_location_client) ; }
			if(!empty($nopvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlNotIn($nopvhtLigne_location_client) ; }
			if(!empty($lt_pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client < '".$lt_pvhtLigne_location_client."'" ; }
			if(!empty($gt_pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client > '".$gt_pvhtLigne_location_client."'" ; }
			if(!empty($idproduit)){ $sql .= " AND idproduit ".sqlIn($idproduit) ; }
			if(!empty($noidproduit)){ $sql .= " AND idproduit ".sqlNotIn($noidproduit) ; }
			if(!empty($lt_idproduit)){ $sql .= " AND idproduit < '".$lt_idproduit."'" ; }
			if(!empty($gt_idproduit)){ $sql .= " AND idproduit > '".$gt_idproduit."'" ; }
			if(!empty($gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlIn($gamme_produit_idgamme_produit) ; }
			if(!empty($nogamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlNotIn($nogamme_produit_idgamme_produit) ; }
			if(!empty($lt_gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit < '".$lt_gamme_produit_idgamme_produit."'" ; }
			if(!empty($gt_gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit > '".$gt_gamme_produit_idgamme_produit."'" ; }
			if(!empty($marque_idmarque)){ $sql .= " AND marque_idmarque ".sqlIn($marque_idmarque) ; }
			if(!empty($nomarque_idmarque)){ $sql .= " AND marque_idmarque ".sqlNotIn($nomarque_idmarque) ; }
			if(!empty($lt_marque_idmarque)){ $sql .= " AND marque_idmarque < '".$lt_marque_idmarque."'" ; }
			if(!empty($gt_marque_idmarque)){ $sql .= " AND marque_idmarque > '".$gt_marque_idmarque."'" ; }
			if(!empty($referenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlIn($referenceInterneProduit) ; }
			if(!empty($noreferenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlNotIn($noreferenceInterneProduit) ; }
			if(!empty($lt_referenceInterneProduit)){ $sql .= " AND referenceInterneProduit < '".$lt_referenceInterneProduit."'" ; }
			if(!empty($gt_referenceInterneProduit)){ $sql .= " AND referenceInterneProduit > '".$gt_referenceInterneProduit."'" ; }
			if(!empty($nomProduit)){ $sql .= " AND nomProduit ".sqlIn($nomProduit) ; }
			if(!empty($nonomProduit)){ $sql .= " AND nomProduit ".sqlNotIn($nonomProduit) ; }
			if(!empty($lt_nomProduit)){ $sql .= " AND nomProduit < '".$lt_nomProduit."'" ; }
			if(!empty($gt_nomProduit)){ $sql .= " AND nomProduit > '".$gt_nomProduit."'" ; }
			if(!empty($pahtProduit)){ $sql .= " AND pahtProduit ".sqlIn($pahtProduit) ; }
			if(!empty($nopahtProduit)){ $sql .= " AND pahtProduit ".sqlNotIn($nopahtProduit) ; }
			if(!empty($lt_pahtProduit)){ $sql .= " AND pahtProduit < '".$lt_pahtProduit."'" ; }
			if(!empty($gt_pahtProduit)){ $sql .= " AND pahtProduit > '".$gt_pahtProduit."'" ; }
			if(!empty($pvhtProduit)){ $sql .= " AND pvhtProduit ".sqlIn($pvhtProduit) ; }
			if(!empty($nopvhtProduit)){ $sql .= " AND pvhtProduit ".sqlNotIn($nopvhtProduit) ; }
			if(!empty($lt_pvhtProduit)){ $sql .= " AND pvhtProduit < '".$lt_pvhtProduit."'" ; }
			if(!empty($gt_pvhtProduit)){ $sql .= " AND pvhtProduit > '".$gt_pvhtProduit."'" ; }
			if(!empty($commentaireProduit)){ $sql .= " AND commentaireProduit ".sqlIn($commentaireProduit) ; }
			if(!empty($nocommentaireProduit)){ $sql .= " AND commentaireProduit ".sqlNotIn($nocommentaireProduit) ; }
			if(!empty($lt_commentaireProduit)){ $sql .= " AND commentaireProduit < '".$lt_commentaireProduit."'" ; }
			if(!empty($gt_commentaireProduit)){ $sql .= " AND commentaireProduit > '".$gt_commentaireProduit."'" ; }
			if(!empty($estActifProduit)){ $sql .= " AND estActifProduit ".sqlIn($estActifProduit) ; }
			if(!empty($noestActifProduit)){ $sql .= " AND estActifProduit ".sqlNotIn($noestActifProduit) ; }
			if(!empty($lt_estActifProduit)){ $sql .= " AND estActifProduit < '".$lt_estActifProduit."'" ; }
			if(!empty($gt_estActifProduit)){ $sql .= " AND estActifProduit > '".$gt_estActifProduit."'" ; }
			if(!empty($qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlIn($qteAlerteStockProduit) ; }
			if(!empty($noqteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlNotIn($noqteAlerteStockProduit) ; }
			if(!empty($lt_qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit < '".$lt_qteAlerteStockProduit."'" ; }
			if(!empty($gt_qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit > '".$gt_qteAlerteStockProduit."'" ; }
			if(!empty($idmateriel)){ $sql .= " AND idmateriel ".sqlIn($idmateriel) ; }
			if(!empty($noidmateriel)){ $sql .= " AND idmateriel ".sqlNotIn($noidmateriel) ; }
			if(!empty($lt_idmateriel)){ $sql .= " AND idmateriel < '".$lt_idmateriel."'" ; }
			if(!empty($gt_idmateriel)){ $sql .= " AND idmateriel > '".$gt_idmateriel."'" ; }
			if(!empty($stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlIn($stock_materiel_idstock_materiel) ; }
			if(!empty($nostock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlNotIn($nostock_materiel_idstock_materiel) ; }
			if(!empty($lt_stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel < '".$lt_stock_materiel_idstock_materiel."'" ; }
			if(!empty($gt_stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel > '".$gt_stock_materiel_idstock_materiel."'" ; }
			if(!empty($produit_idproduit)){ $sql .= " AND produit_idproduit ".sqlIn($produit_idproduit) ; }
			if(!empty($noproduit_idproduit)){ $sql .= " AND produit_idproduit ".sqlNotIn($noproduit_idproduit) ; }
			if(!empty($lt_produit_idproduit)){ $sql .= " AND produit_idproduit < '".$lt_produit_idproduit."'" ; }
			if(!empty($gt_produit_idproduit)){ $sql .= " AND produit_idproduit > '".$gt_produit_idproduit."'" ; }
			if(!empty($numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlIn($numeroSerieInterneMateriel) ; }
			if(!empty($nonumeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlNotIn($nonumeroSerieInterneMateriel) ; }
			if(!empty($lt_numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel < '".$lt_numeroSerieInterneMateriel."'" ; }
			if(!empty($gt_numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel > '".$gt_numeroSerieInterneMateriel."'" ; }
			if(!empty($numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlIn($numeroSerieExterneMateriel) ; }
			if(!empty($nonumeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlNotIn($nonumeroSerieExterneMateriel) ; }
			if(!empty($lt_numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel < '".$lt_numeroSerieExterneMateriel."'" ; }
			if(!empty($gt_numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel > '".$gt_numeroSerieExterneMateriel."'" ; }
			if(!empty($dateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlIn($dateCreationMateriel) ; }
			if(!empty($nodateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlNotIn($nodateCreationMateriel) ; }
			if(!empty($lt_dateCreationMateriel)){ $sql .= " AND dateCreationMateriel < '".$lt_dateCreationMateriel."'" ; }
			if(!empty($gt_dateCreationMateriel)){ $sql .= " AND dateCreationMateriel > '".$gt_dateCreationMateriel."'" ; }
			if(!empty($dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlIn($dateAcquisitionMateriel) ; }
			if(!empty($nodateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlNotIn($nodateAcquisitionMateriel) ; }
			if(!empty($lt_dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel < '".$lt_dateAcquisitionMateriel."'" ; }
			if(!empty($gt_dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel > '".$gt_dateAcquisitionMateriel."'" ; }
			if(!empty($dateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlIn($dateFinMateriel) ; }
			if(!empty($nodateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlNotIn($nodateFinMateriel) ; }
			if(!empty($lt_dateFinMateriel)){ $sql .= " AND dateFinMateriel < '".$lt_dateFinMateriel."'" ; }
			if(!empty($gt_dateFinMateriel)){ $sql .= " AND dateFinMateriel > '".$gt_dateFinMateriel."'" ; }
			if(!empty($estActifMateriel)){ $sql .= " AND estActifMateriel ".sqlIn($estActifMateriel) ; }
			if(!empty($noestActifMateriel)){ $sql .= " AND estActifMateriel ".sqlNotIn($noestActifMateriel) ; }
			if(!empty($lt_estActifMateriel)){ $sql .= " AND estActifMateriel < '".$lt_estActifMateriel."'" ; }
			if(!empty($gt_estActifMateriel)){ $sql .= " AND estActifMateriel > '".$gt_estActifMateriel."'" ; }
			if(!empty($pahtMateriel)){ $sql .= " AND pahtMateriel ".sqlIn($pahtMateriel) ; }
			if(!empty($nopahtMateriel)){ $sql .= " AND pahtMateriel ".sqlNotIn($nopahtMateriel) ; }
			if(!empty($lt_pahtMateriel)){ $sql .= " AND pahtMateriel < '".$lt_pahtMateriel."'" ; }
			if(!empty($gt_pahtMateriel)){ $sql .= " AND pahtMateriel > '".$gt_pahtMateriel."'" ; }
			if(!empty($pvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlIn($pvhtMateriel) ; }
			if(!empty($nopvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlNotIn($nopvhtMateriel) ; }
			if(!empty($lt_pvhtMateriel)){ $sql .= " AND pvhtMateriel < '".$lt_pvhtMateriel."'" ; }
			if(!empty($gt_pvhtMateriel)){ $sql .= " AND pvhtMateriel > '".$gt_pvhtMateriel."'" ; }
			if(!empty($commentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlIn($commentaireMateriel) ; }
			if(!empty($nocommentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlNotIn($nocommentaireMateriel) ; }
			if(!empty($lt_commentaireMateriel)){ $sql .= " AND commentaireMateriel < '".$lt_commentaireMateriel."'" ; }
			if(!empty($gt_commentaireMateriel)){ $sql .= " AND commentaireMateriel > '".$gt_commentaireMateriel."'" ; }
			if(!empty($idsociete)){ $sql .= " AND idsociete ".sqlIn($idsociete) ; }
			if(!empty($noidsociete)){ $sql .= " AND idsociete ".sqlNotIn($noidsociete) ; }
			if(!empty($lt_idsociete)){ $sql .= " AND idsociete < '".$lt_idsociete."'" ; }
			if(!empty($gt_idsociete)){ $sql .= " AND idsociete > '".$gt_idsociete."'" ; }
			if(!empty($nomSociete)){ $sql .= " AND nomSociete ".sqlIn($nomSociete) ; }
			if(!empty($nonomSociete)){ $sql .= " AND nomSociete ".sqlNotIn($nonomSociete) ; }
			if(!empty($lt_nomSociete)){ $sql .= " AND nomSociete < '".$lt_nomSociete."'" ; }
			if(!empty($gt_nomSociete)){ $sql .= " AND nomSociete > '".$gt_nomSociete."'" ; }
			if(!empty($siretSociete)){ $sql .= " AND siretSociete ".sqlIn($siretSociete) ; }
			if(!empty($nosiretSociete)){ $sql .= " AND siretSociete ".sqlNotIn($nosiretSociete) ; }
			if(!empty($lt_siretSociete)){ $sql .= " AND siretSociete < '".$lt_siretSociete."'" ; }
			if(!empty($gt_siretSociete)){ $sql .= " AND siretSociete > '".$gt_siretSociete."'" ; }
			if(!empty($sirenSociete)){ $sql .= " AND sirenSociete ".sqlIn($sirenSociete) ; }
			if(!empty($nosirenSociete)){ $sql .= " AND sirenSociete ".sqlNotIn($nosirenSociete) ; }
			if(!empty($lt_sirenSociete)){ $sql .= " AND sirenSociete < '".$lt_sirenSociete."'" ; }
			if(!empty($gt_sirenSociete)){ $sql .= " AND sirenSociete > '".$gt_sirenSociete."'" ; }
			if(!empty($apeSociete)){ $sql .= " AND apeSociete ".sqlIn($apeSociete) ; }
			if(!empty($noapeSociete)){ $sql .= " AND apeSociete ".sqlNotIn($noapeSociete) ; }
			if(!empty($lt_apeSociete)){ $sql .= " AND apeSociete < '".$lt_apeSociete."'" ; }
			if(!empty($gt_apeSociete)){ $sql .= " AND apeSociete > '".$gt_apeSociete."'" ; }
			if(!empty($tvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlIn($tvaIntraSociete) ; }
			if(!empty($notvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlNotIn($notvaIntraSociete) ; }
			if(!empty($lt_tvaIntraSociete)){ $sql .= " AND tvaIntraSociete < '".$lt_tvaIntraSociete."'" ; }
			if(!empty($gt_tvaIntraSociete)){ $sql .= " AND tvaIntraSociete > '".$gt_tvaIntraSociete."'" ; }
			if(!empty($formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlIn($formeJuridiqueSociete) ; }
			if(!empty($noformeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlNotIn($noformeJuridiqueSociete) ; }
			if(!empty($lt_formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete < '".$lt_formeJuridiqueSociete."'" ; }
			if(!empty($gt_formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete > '".$gt_formeJuridiqueSociete."'" ; }
			if(!empty($capitalSociete)){ $sql .= " AND capitalSociete ".sqlIn($capitalSociete) ; }
			if(!empty($nocapitalSociete)){ $sql .= " AND capitalSociete ".sqlNotIn($nocapitalSociete) ; }
			if(!empty($lt_capitalSociete)){ $sql .= " AND capitalSociete < '".$lt_capitalSociete."'" ; }
			if(!empty($gt_capitalSociete)){ $sql .= " AND capitalSociete > '".$gt_capitalSociete."'" ; }
			if(!empty($deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlIn($deviseCapitalSociete) ; }
			if(!empty($nodeviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlNotIn($nodeviseCapitalSociete) ; }
			if(!empty($lt_deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete < '".$lt_deviseCapitalSociete."'" ; }
			if(!empty($gt_deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete > '".$gt_deviseCapitalSociete."'" ; }
			if(!empty($deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlIn($deviseFacturationSociete) ; }
			if(!empty($nodeviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlNotIn($nodeviseFacturationSociete) ; }
			if(!empty($lt_deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete < '".$lt_deviseFacturationSociete."'" ; }
			if(!empty($gt_deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete > '".$gt_deviseFacturationSociete."'" ; }
			if(!empty($activiteSociete)){ $sql .= " AND activiteSociete ".sqlIn($activiteSociete) ; }
			if(!empty($noactiviteSociete)){ $sql .= " AND activiteSociete ".sqlNotIn($noactiviteSociete) ; }
			if(!empty($lt_activiteSociete)){ $sql .= " AND activiteSociete < '".$lt_activiteSociete."'" ; }
			if(!empty($gt_activiteSociete)){ $sql .= " AND activiteSociete > '".$gt_activiteSociete."'" ; }
			if(!empty($chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlIn($chiffreAffaireSociete) ; }
			if(!empty($nochiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlNotIn($nochiffreAffaireSociete) ; }
			if(!empty($lt_chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete < '".$lt_chiffreAffaireSociete."'" ; }
			if(!empty($gt_chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete > '".$gt_chiffreAffaireSociete."'" ; }
			if(!empty($nbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlIn($nbSalarieSociete) ; }
			if(!empty($nonbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlNotIn($nonbSalarieSociete) ; }
			if(!empty($lt_nbSalarieSociete)){ $sql .= " AND nbSalarieSociete < '".$lt_nbSalarieSociete."'" ; }
			if(!empty($gt_nbSalarieSociete)){ $sql .= " AND nbSalarieSociete > '".$gt_nbSalarieSociete."'" ; }
			if(!empty($beneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlIn($beneficeSocitete) ; }
			if(!empty($nobeneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlNotIn($nobeneficeSocitete) ; }
			if(!empty($lt_beneficeSocitete)){ $sql .= " AND beneficeSocitete < '".$lt_beneficeSocitete."'" ; }
			if(!empty($gt_beneficeSocitete)){ $sql .= " AND beneficeSocitete > '".$gt_beneficeSocitete."'" ; }
			if(!empty($estFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlIn($estFacturableSociete) ; }
			if(!empty($noestFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlNotIn($noestFacturableSociete) ; }
			if(!empty($lt_estFacturableSociete)){ $sql .= " AND estFacturableSociete < '".$lt_estFacturableSociete."'" ; }
			if(!empty($gt_estFacturableSociete)){ $sql .= " AND estFacturableSociete > '".$gt_estFacturableSociete."'" ; }
			if(!empty($idclient)){ $sql .= " AND idclient ".sqlIn($idclient) ; }
			if(!empty($noidclient)){ $sql .= " AND idclient ".sqlNotIn($noidclient) ; }
			if(!empty($lt_idclient)){ $sql .= " AND idclient < '".$lt_idclient."'" ; }
			if(!empty($gt_idclient)){ $sql .= " AND idclient > '".$gt_idclient."'" ; }
			if(!empty($societe_idsociete)){ $sql .= " AND societe_idsociete ".sqlIn($societe_idsociete) ; }
			if(!empty($nosociete_idsociete)){ $sql .= " AND societe_idsociete ".sqlNotIn($nosociete_idsociete) ; }
			if(!empty($lt_societe_idsociete)){ $sql .= " AND societe_idsociete < '".$lt_societe_idsociete."'" ; }
			if(!empty($gt_societe_idsociete)){ $sql .= " AND societe_idsociete > '".$gt_societe_idsociete."'" ; }
			if(!empty($nomType_location_client)){ $sql .= " AND nomType_location_client ".sqlIn($nomType_location_client) ; }
			if(!empty($nonomType_location_client)){ $sql .= " AND nomType_location_client ".sqlNotIn($nonomType_location_client) ; }
			if(!empty($lt_nomType_location_client)){ $sql .= " AND nomType_location_client < '".$lt_nomType_location_client."'" ; }
			if(!empty($gt_nomType_location_client)){ $sql .= " AND nomType_location_client > '".$gt_nomType_location_client."'" ; }
			if(!empty($idtype_location_client)){ $sql .= " AND idtype_location_client ".sqlIn($idtype_location_client) ; }
			if(!empty($noidtype_location_client)){ $sql .= " AND idtype_location_client ".sqlNotIn($noidtype_location_client) ; }
			if(!empty($lt_idtype_location_client)){ $sql .= " AND idtype_location_client < '".$lt_idtype_location_client."'" ; }
			if(!empty($gt_idtype_location_client)){ $sql .= " AND idtype_location_client > '".$gt_idtype_location_client."'" ; }
			if(!empty($numContrat)){ $sql .= " AND numContrat ".sqlIn($numContrat) ; }
			if(!empty($nonumContrat)){ $sql .= " AND numContrat ".sqlNotIn($nonumContrat) ; }
			if(!empty($lt_numContrat)){ $sql .= " AND numContrat < '".$lt_numContrat."'" ; }
			if(!empty($gt_numContrat)){ $sql .= " AND numContrat > '".$gt_numContrat."'" ; }
			if(!empty($dureeContrat)){ $sql .= " AND dureeContrat ".sqlIn($dureeContrat) ; }
			if(!empty($nodureeContrat)){ $sql .= " AND dureeContrat ".sqlNotIn($nodureeContrat) ; }
			if(!empty($lt_dureeContrat)){ $sql .= " AND dureeContrat < '".$lt_dureeContrat."'" ; }
			if(!empty($gt_dureeContrat)){ $sql .= " AND dureeContrat > '".$gt_dureeContrat."'" ; }
			if(!empty($dateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlIn($dateDebutContrat) ; }
			if(!empty($nodateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlNotIn($nodateDebutContrat) ; }
			if(!empty($lt_dateDebutContrat)){ $sql .= " AND dateDebutContrat < '".$lt_dateDebutContrat."'" ; }
			if(!empty($gt_dateDebutContrat)){ $sql .= " AND dateDebutContrat > '".$gt_dateDebutContrat."'" ; }
			if(!empty($type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlIn($type_contrat_idtype_contrat) ; }
			if(!empty($notype_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlNotIn($notype_contrat_idtype_contrat) ; }
			if(!empty($lt_type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat < '".$lt_type_contrat_idtype_contrat."'" ; }
			if(!empty($gt_type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat > '".$gt_type_contrat_idtype_contrat."'" ; }
			if(!empty($adresse1)){ $sql .= " AND adresse1 ".sqlIn($adresse1) ; }
			if(!empty($noadresse1)){ $sql .= " AND adresse1 ".sqlNotIn($noadresse1) ; }
			if(!empty($lt_adresse1)){ $sql .= " AND adresse1 < '".$lt_adresse1."'" ; }
			if(!empty($gt_adresse1)){ $sql .= " AND adresse1 > '".$gt_adresse1."'" ; }
			if(!empty($adresse2)){ $sql .= " AND adresse2 ".sqlIn($adresse2) ; }
			if(!empty($noadresse2)){ $sql .= " AND adresse2 ".sqlNotIn($noadresse2) ; }
			if(!empty($lt_adresse2)){ $sql .= " AND adresse2 < '".$lt_adresse2."'" ; }
			if(!empty($gt_adresse2)){ $sql .= " AND adresse2 > '".$gt_adresse2."'" ; }
			if(!empty($codePostalAdresse)){ $sql .= " AND codePostalAdresse ".sqlIn($codePostalAdresse) ; }
			if(!empty($nocodePostalAdresse)){ $sql .= " AND codePostalAdresse ".sqlNotIn($nocodePostalAdresse) ; }
			if(!empty($lt_codePostalAdresse)){ $sql .= " AND codePostalAdresse < '".$lt_codePostalAdresse."'" ; }
			if(!empty($gt_codePostalAdresse)){ $sql .= " AND codePostalAdresse > '".$gt_codePostalAdresse."'" ; }
			if(!empty($villeAdresse)){ $sql .= " AND villeAdresse ".sqlIn($villeAdresse) ; }
			if(!empty($novilleAdresse)){ $sql .= " AND villeAdresse ".sqlNotIn($novilleAdresse) ; }
			if(!empty($lt_villeAdresse)){ $sql .= " AND villeAdresse < '".$lt_villeAdresse."'" ; }
			if(!empty($gt_villeAdresse)){ $sql .= " AND villeAdresse > '".$gt_villeAdresse."'" ; }
			if(!empty($contrat_idcontrat)){ $sql .= " AND contrat_idcontrat ".sqlIn($contrat_idcontrat) ; }
			if(!empty($nocontrat_idcontrat)){ $sql .= " AND contrat_idcontrat ".sqlNotIn($nocontrat_idcontrat) ; }
			if(!empty($lt_contrat_idcontrat)){ $sql .= " AND contrat_idcontrat < '".$lt_contrat_idcontrat."'" ; }
			if(!empty($gt_contrat_idcontrat)){ $sql .= " AND contrat_idcontrat > '".$gt_contrat_idcontrat."'" ; }
			
			if(!empty($agent_idagent)){ $sql .= " AND agent_idagent ".sqlSearch($agent_idagent) ; }
			if(!empty($noagent_idagent)){ $sql .= " AND agent_idagent ".sqlNotSearch($noagent_idagent) ; }
			
			if(!empty($groupBy)){ $sql .= " group by $groupBy";  }
			if(!empty($orderBy)){ $sql .= " order by $orderBy";  }
			if(!empty($debug)){ echo $sql;   }
			if(!empty($nbRows) && !empty($page) ){ return $this->conn ->PageExecute($sql,$nbRows,$page);}
	return $this->conn->Execute($sql) ;	
	}
	function searchOneSearchLocationClient($params){
		extract($params,EXTR_OVERWRITE) ;	
		$sql="select * from vue_search_location_client where 1 " ;
			if(!empty($idlocation_client)){ $sql .= " AND idlocation_client ".sqlSearch($idlocation_client,"idlocation_client") ; }
			if(!empty($lt_idlocation_client)){ $sql .= " AND idlocation_client < '".$lt_idlocation_client."'" ; }
			if(!empty($gt_idlocation_client)){ $sql .= " AND idlocation_client > '".$gt_idlocation_client."'" ; }
			if(!empty($noidlocation_client)){ $sql .= " AND idlocation_client ".sqlNotSearch($noidlocation_client) ; }
			if(!empty($type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlSearch($type_location_client_idtype_location_client,"type_location_client_idtype_location_client") ; }
			if(!empty($lt_type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client < '".$lt_type_location_client_idtype_location_client."'" ; }
			if(!empty($gt_type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client > '".$gt_type_location_client_idtype_location_client."'" ; }
			if(!empty($notype_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlNotSearch($notype_location_client_idtype_location_client) ; }
			if(!empty($client_idclient)){ $sql .= " AND client_idclient ".sqlSearch($client_idclient,"client_idclient") ; }
			if(!empty($lt_client_idclient)){ $sql .= " AND client_idclient < '".$lt_client_idclient."'" ; }
			if(!empty($gt_client_idclient)){ $sql .= " AND client_idclient > '".$gt_client_idclient."'" ; }
			if(!empty($noclient_idclient)){ $sql .= " AND client_idclient ".sqlNotSearch($noclient_idclient) ; }
			if(!empty($numeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlSearch($numeroLocation_client,"numeroLocation_client") ; }
			if(!empty($lt_numeroLocation_client)){ $sql .= " AND numeroLocation_client < '".$lt_numeroLocation_client."'" ; }
			if(!empty($gt_numeroLocation_client)){ $sql .= " AND numeroLocation_client > '".$gt_numeroLocation_client."'" ; }
			if(!empty($nonumeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlNotSearch($nonumeroLocation_client) ; }
			if(!empty($dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlSearch($dateCreationLocation_client,"dateCreationLocation_client") ; }
			if(!empty($lt_dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client < '".$lt_dateCreationLocation_client."'" ; }
			if(!empty($gt_dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client > '".$gt_dateCreationLocation_client."'" ; }
			if(!empty($nodateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlNotSearch($nodateCreationLocation_client) ; }
			if(!empty($dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlSearch($dateDebutLocation_client,"dateDebutLocation_client") ; }
			if(!empty($lt_dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client < '".$lt_dateDebutLocation_client."'" ; }
			if(!empty($gt_dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client > '".$gt_dateDebutLocation_client."'" ; }
			if(!empty($nodateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlNotSearch($nodateDebutLocation_client) ; }
			if(!empty($dateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlSearch($dateFinLocation_client,"dateFinLocation_client") ; }
			if(!empty($lt_dateFinLocation_client)){ $sql .= " AND dateFinLocation_client < '".$lt_dateFinLocation_client."'" ; }
			if(!empty($gt_dateFinLocation_client)){ $sql .= " AND dateFinLocation_client > '".$gt_dateFinLocation_client."'" ; }
			if(!empty($nodateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlNotSearch($nodateFinLocation_client) ; }
			if(!empty($dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlSearch($dateClotureLocation_client,"dateClotureLocation_client") ; }
			if(!empty($lt_dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client < '".$lt_dateClotureLocation_client."'" ; }
			if(!empty($gt_dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client > '".$gt_dateClotureLocation_client."'" ; }
			if(!empty($nodateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlNotSearch($nodateClotureLocation_client) ; }
			if(!empty($idligne_location_client)){ $sql .= " AND idligne_location_client ".sqlSearch($idligne_location_client,"idligne_location_client") ; }
			if(!empty($lt_idligne_location_client)){ $sql .= " AND idligne_location_client < '".$lt_idligne_location_client."'" ; }
			if(!empty($gt_idligne_location_client)){ $sql .= " AND idligne_location_client > '".$gt_idligne_location_client."'" ; }
			if(!empty($noidligne_location_client)){ $sql .= " AND idligne_location_client ".sqlNotSearch($noidligne_location_client) ; }
			if(!empty($localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlSearch($localisation_idlocalisation,"localisation_idlocalisation") ; }
			if(!empty($lt_localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation < '".$lt_localisation_idlocalisation."'" ; }
			if(!empty($gt_localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation > '".$gt_localisation_idlocalisation."'" ; }
			if(!empty($nolocalisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlNotSearch($nolocalisation_idlocalisation) ; }
			if(!empty($materiel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlSearch($materiel_idmateriel,"materiel_idmateriel") ; }
			if(!empty($lt_materiel_idmateriel)){ $sql .= " AND materiel_idmateriel < '".$lt_materiel_idmateriel."'" ; }
			if(!empty($gt_materiel_idmateriel)){ $sql .= " AND materiel_idmateriel > '".$gt_materiel_idmateriel."'" ; }
			if(!empty($nomateriel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlNotSearch($nomateriel_idmateriel) ; }
			if(!empty($location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlSearch($location_client_idlocation_client,"location_client_idlocation_client") ; }
			if(!empty($lt_location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client < '".$lt_location_client_idlocation_client."'" ; }
			if(!empty($gt_location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client > '".$gt_location_client_idlocation_client."'" ; }
			if(!empty($nolocation_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlNotSearch($nolocation_client_idlocation_client) ; }
			if(!empty($dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlSearch($dateCreationLigne_location_client,"dateCreationLigne_location_client") ; }
			if(!empty($lt_dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client < '".$lt_dateCreationLigne_location_client."'" ; }
			if(!empty($gt_dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client > '".$gt_dateCreationLigne_location_client."'" ; }
			if(!empty($nodateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlNotSearch($nodateCreationLigne_location_client) ; }
			if(!empty($dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlSearch($dateDebutLigne_location_client,"dateDebutLigne_location_client") ; }
			if(!empty($lt_dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client < '".$lt_dateDebutLigne_location_client."'" ; }
			if(!empty($gt_dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client > '".$gt_dateDebutLigne_location_client."'" ; }
			if(!empty($nodateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlNotSearch($nodateDebutLigne_location_client) ; }
			if(!empty($dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlSearch($dateClotureLigne_location_client,"dateClotureLigne_location_client") ; }
			if(!empty($lt_dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client < '".$lt_dateClotureLigne_location_client."'" ; }
			if(!empty($gt_dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client > '".$gt_dateClotureLigne_location_client."'" ; }
			if(!empty($nodateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlNotSearch($nodateClotureLigne_location_client) ; }
			if(!empty($dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlSearch($dateFinLigne_location_client,"dateFinLigne_location_client") ; }
			if(!empty($lt_dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client < '".$lt_dateFinLigne_location_client."'" ; }
			if(!empty($gt_dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client > '".$gt_dateFinLigne_location_client."'" ; }
			if(!empty($nodateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlNotSearch($nodateFinLigne_location_client) ; }
			if(!empty($dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlSearch($dureeLigne_location_client,"dureeLigne_location_client") ; }
			if(!empty($lt_dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client < '".$lt_dureeLigne_location_client."'" ; }
			if(!empty($gt_dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client > '".$gt_dureeLigne_location_client."'" ; }
			if(!empty($nodureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlNotSearch($nodureeLigne_location_client) ; }
			if(!empty($uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlSearch($uniteDureeLigne_location_client,"uniteDureeLigne_location_client") ; }
			if(!empty($lt_uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client < '".$lt_uniteDureeLigne_location_client."'" ; }
			if(!empty($gt_uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client > '".$gt_uniteDureeLigne_location_client."'" ; }
			if(!empty($nouniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlNotSearch($nouniteDureeLigne_location_client) ; }
			if(!empty($pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlSearch($pvhtLigne_location_client,"pvhtLigne_location_client") ; }
			if(!empty($lt_pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client < '".$lt_pvhtLigne_location_client."'" ; }
			if(!empty($gt_pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client > '".$gt_pvhtLigne_location_client."'" ; }
			if(!empty($nopvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlNotSearch($nopvhtLigne_location_client) ; }
			if(!empty($idproduit)){ $sql .= " AND idproduit ".sqlSearch($idproduit,"idproduit") ; }
			if(!empty($lt_idproduit)){ $sql .= " AND idproduit < '".$lt_idproduit."'" ; }
			if(!empty($gt_idproduit)){ $sql .= " AND idproduit > '".$gt_idproduit."'" ; }
			if(!empty($noidproduit)){ $sql .= " AND idproduit ".sqlNotSearch($noidproduit) ; }
			if(!empty($gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlSearch($gamme_produit_idgamme_produit,"gamme_produit_idgamme_produit") ; }
			if(!empty($lt_gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit < '".$lt_gamme_produit_idgamme_produit."'" ; }
			if(!empty($gt_gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit > '".$gt_gamme_produit_idgamme_produit."'" ; }
			if(!empty($nogamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlNotSearch($nogamme_produit_idgamme_produit) ; }
			if(!empty($marque_idmarque)){ $sql .= " AND marque_idmarque ".sqlSearch($marque_idmarque,"marque_idmarque") ; }
			if(!empty($lt_marque_idmarque)){ $sql .= " AND marque_idmarque < '".$lt_marque_idmarque."'" ; }
			if(!empty($gt_marque_idmarque)){ $sql .= " AND marque_idmarque > '".$gt_marque_idmarque."'" ; }
			if(!empty($nomarque_idmarque)){ $sql .= " AND marque_idmarque ".sqlNotSearch($nomarque_idmarque) ; }
			if(!empty($referenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlSearch($referenceInterneProduit,"referenceInterneProduit") ; }
			if(!empty($lt_referenceInterneProduit)){ $sql .= " AND referenceInterneProduit < '".$lt_referenceInterneProduit."'" ; }
			if(!empty($gt_referenceInterneProduit)){ $sql .= " AND referenceInterneProduit > '".$gt_referenceInterneProduit."'" ; }
			if(!empty($noreferenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlNotSearch($noreferenceInterneProduit) ; }
			if(!empty($nomProduit)){ $sql .= " AND nomProduit ".sqlSearch($nomProduit,"nomProduit") ; }
			if(!empty($lt_nomProduit)){ $sql .= " AND nomProduit < '".$lt_nomProduit."'" ; }
			if(!empty($gt_nomProduit)){ $sql .= " AND nomProduit > '".$gt_nomProduit."'" ; }
			if(!empty($nonomProduit)){ $sql .= " AND nomProduit ".sqlNotSearch($nonomProduit) ; }
			if(!empty($pahtProduit)){ $sql .= " AND pahtProduit ".sqlSearch($pahtProduit,"pahtProduit") ; }
			if(!empty($lt_pahtProduit)){ $sql .= " AND pahtProduit < '".$lt_pahtProduit."'" ; }
			if(!empty($gt_pahtProduit)){ $sql .= " AND pahtProduit > '".$gt_pahtProduit."'" ; }
			if(!empty($nopahtProduit)){ $sql .= " AND pahtProduit ".sqlNotSearch($nopahtProduit) ; }
			if(!empty($pvhtProduit)){ $sql .= " AND pvhtProduit ".sqlSearch($pvhtProduit,"pvhtProduit") ; }
			if(!empty($lt_pvhtProduit)){ $sql .= " AND pvhtProduit < '".$lt_pvhtProduit."'" ; }
			if(!empty($gt_pvhtProduit)){ $sql .= " AND pvhtProduit > '".$gt_pvhtProduit."'" ; }
			if(!empty($nopvhtProduit)){ $sql .= " AND pvhtProduit ".sqlNotSearch($nopvhtProduit) ; }
			if(!empty($commentaireProduit)){ $sql .= " AND commentaireProduit ".sqlSearch($commentaireProduit,"commentaireProduit") ; }
			if(!empty($lt_commentaireProduit)){ $sql .= " AND commentaireProduit < '".$lt_commentaireProduit."'" ; }
			if(!empty($gt_commentaireProduit)){ $sql .= " AND commentaireProduit > '".$gt_commentaireProduit."'" ; }
			if(!empty($nocommentaireProduit)){ $sql .= " AND commentaireProduit ".sqlNotSearch($nocommentaireProduit) ; }
			if(!empty($estActifProduit)){ $sql .= " AND estActifProduit ".sqlSearch($estActifProduit,"estActifProduit") ; }
			if(!empty($lt_estActifProduit)){ $sql .= " AND estActifProduit < '".$lt_estActifProduit."'" ; }
			if(!empty($gt_estActifProduit)){ $sql .= " AND estActifProduit > '".$gt_estActifProduit."'" ; }
			if(!empty($noestActifProduit)){ $sql .= " AND estActifProduit ".sqlNotSearch($noestActifProduit) ; }
			if(!empty($qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlSearch($qteAlerteStockProduit,"qteAlerteStockProduit") ; }
			if(!empty($lt_qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit < '".$lt_qteAlerteStockProduit."'" ; }
			if(!empty($gt_qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit > '".$gt_qteAlerteStockProduit."'" ; }
			if(!empty($noqteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlNotSearch($noqteAlerteStockProduit) ; }
			if(!empty($idmateriel)){ $sql .= " AND idmateriel ".sqlSearch($idmateriel,"idmateriel") ; }
			if(!empty($lt_idmateriel)){ $sql .= " AND idmateriel < '".$lt_idmateriel."'" ; }
			if(!empty($gt_idmateriel)){ $sql .= " AND idmateriel > '".$gt_idmateriel."'" ; }
			if(!empty($noidmateriel)){ $sql .= " AND idmateriel ".sqlNotSearch($noidmateriel) ; }
			if(!empty($stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlSearch($stock_materiel_idstock_materiel,"stock_materiel_idstock_materiel") ; }
			if(!empty($lt_stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel < '".$lt_stock_materiel_idstock_materiel."'" ; }
			if(!empty($gt_stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel > '".$gt_stock_materiel_idstock_materiel."'" ; }
			if(!empty($nostock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlNotSearch($nostock_materiel_idstock_materiel) ; }
			if(!empty($produit_idproduit)){ $sql .= " AND produit_idproduit ".sqlSearch($produit_idproduit,"produit_idproduit") ; }
			if(!empty($lt_produit_idproduit)){ $sql .= " AND produit_idproduit < '".$lt_produit_idproduit."'" ; }
			if(!empty($gt_produit_idproduit)){ $sql .= " AND produit_idproduit > '".$gt_produit_idproduit."'" ; }
			if(!empty($noproduit_idproduit)){ $sql .= " AND produit_idproduit ".sqlNotSearch($noproduit_idproduit) ; }
			if(!empty($numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlSearch($numeroSerieInterneMateriel,"numeroSerieInterneMateriel") ; }
			if(!empty($lt_numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel < '".$lt_numeroSerieInterneMateriel."'" ; }
			if(!empty($gt_numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel > '".$gt_numeroSerieInterneMateriel."'" ; }
			if(!empty($nonumeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlNotSearch($nonumeroSerieInterneMateriel) ; }
			if(!empty($numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlSearch($numeroSerieExterneMateriel,"numeroSerieExterneMateriel") ; }
			if(!empty($lt_numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel < '".$lt_numeroSerieExterneMateriel."'" ; }
			if(!empty($gt_numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel > '".$gt_numeroSerieExterneMateriel."'" ; }
			if(!empty($nonumeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlNotSearch($nonumeroSerieExterneMateriel) ; }
			if(!empty($dateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlSearch($dateCreationMateriel,"dateCreationMateriel") ; }
			if(!empty($lt_dateCreationMateriel)){ $sql .= " AND dateCreationMateriel < '".$lt_dateCreationMateriel."'" ; }
			if(!empty($gt_dateCreationMateriel)){ $sql .= " AND dateCreationMateriel > '".$gt_dateCreationMateriel."'" ; }
			if(!empty($nodateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlNotSearch($nodateCreationMateriel) ; }
			if(!empty($dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlSearch($dateAcquisitionMateriel,"dateAcquisitionMateriel") ; }
			if(!empty($lt_dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel < '".$lt_dateAcquisitionMateriel."'" ; }
			if(!empty($gt_dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel > '".$gt_dateAcquisitionMateriel."'" ; }
			if(!empty($nodateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlNotSearch($nodateAcquisitionMateriel) ; }
			if(!empty($dateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlSearch($dateFinMateriel,"dateFinMateriel") ; }
			if(!empty($lt_dateFinMateriel)){ $sql .= " AND dateFinMateriel < '".$lt_dateFinMateriel."'" ; }
			if(!empty($gt_dateFinMateriel)){ $sql .= " AND dateFinMateriel > '".$gt_dateFinMateriel."'" ; }
			if(!empty($nodateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlNotSearch($nodateFinMateriel) ; }
			if(!empty($estActifMateriel)){ $sql .= " AND estActifMateriel ".sqlSearch($estActifMateriel,"estActifMateriel") ; }
			if(!empty($lt_estActifMateriel)){ $sql .= " AND estActifMateriel < '".$lt_estActifMateriel."'" ; }
			if(!empty($gt_estActifMateriel)){ $sql .= " AND estActifMateriel > '".$gt_estActifMateriel."'" ; }
			if(!empty($noestActifMateriel)){ $sql .= " AND estActifMateriel ".sqlNotSearch($noestActifMateriel) ; }
			if(!empty($pahtMateriel)){ $sql .= " AND pahtMateriel ".sqlSearch($pahtMateriel,"pahtMateriel") ; }
			if(!empty($lt_pahtMateriel)){ $sql .= " AND pahtMateriel < '".$lt_pahtMateriel."'" ; }
			if(!empty($gt_pahtMateriel)){ $sql .= " AND pahtMateriel > '".$gt_pahtMateriel."'" ; }
			if(!empty($nopahtMateriel)){ $sql .= " AND pahtMateriel ".sqlNotSearch($nopahtMateriel) ; }
			if(!empty($pvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlSearch($pvhtMateriel,"pvhtMateriel") ; }
			if(!empty($lt_pvhtMateriel)){ $sql .= " AND pvhtMateriel < '".$lt_pvhtMateriel."'" ; }
			if(!empty($gt_pvhtMateriel)){ $sql .= " AND pvhtMateriel > '".$gt_pvhtMateriel."'" ; }
			if(!empty($nopvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlNotSearch($nopvhtMateriel) ; }
			if(!empty($commentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlSearch($commentaireMateriel,"commentaireMateriel") ; }
			if(!empty($lt_commentaireMateriel)){ $sql .= " AND commentaireMateriel < '".$lt_commentaireMateriel."'" ; }
			if(!empty($gt_commentaireMateriel)){ $sql .= " AND commentaireMateriel > '".$gt_commentaireMateriel."'" ; }
			if(!empty($nocommentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlNotSearch($nocommentaireMateriel) ; }
			if(!empty($idsociete)){ $sql .= " AND idsociete ".sqlSearch($idsociete,"idsociete") ; }
			if(!empty($lt_idsociete)){ $sql .= " AND idsociete < '".$lt_idsociete."'" ; }
			if(!empty($gt_idsociete)){ $sql .= " AND idsociete > '".$gt_idsociete."'" ; }
			if(!empty($noidsociete)){ $sql .= " AND idsociete ".sqlNotSearch($noidsociete) ; }
			if(!empty($nomSociete)){ $sql .= " AND nomSociete ".sqlSearch($nomSociete,"nomSociete") ; }
			if(!empty($lt_nomSociete)){ $sql .= " AND nomSociete < '".$lt_nomSociete."'" ; }
			if(!empty($gt_nomSociete)){ $sql .= " AND nomSociete > '".$gt_nomSociete."'" ; }
			if(!empty($nonomSociete)){ $sql .= " AND nomSociete ".sqlNotSearch($nonomSociete) ; }
			if(!empty($siretSociete)){ $sql .= " AND siretSociete ".sqlSearch($siretSociete,"siretSociete") ; }
			if(!empty($lt_siretSociete)){ $sql .= " AND siretSociete < '".$lt_siretSociete."'" ; }
			if(!empty($gt_siretSociete)){ $sql .= " AND siretSociete > '".$gt_siretSociete."'" ; }
			if(!empty($nosiretSociete)){ $sql .= " AND siretSociete ".sqlNotSearch($nosiretSociete) ; }
			if(!empty($sirenSociete)){ $sql .= " AND sirenSociete ".sqlSearch($sirenSociete,"sirenSociete") ; }
			if(!empty($lt_sirenSociete)){ $sql .= " AND sirenSociete < '".$lt_sirenSociete."'" ; }
			if(!empty($gt_sirenSociete)){ $sql .= " AND sirenSociete > '".$gt_sirenSociete."'" ; }
			if(!empty($nosirenSociete)){ $sql .= " AND sirenSociete ".sqlNotSearch($nosirenSociete) ; }
			if(!empty($apeSociete)){ $sql .= " AND apeSociete ".sqlSearch($apeSociete,"apeSociete") ; }
			if(!empty($lt_apeSociete)){ $sql .= " AND apeSociete < '".$lt_apeSociete."'" ; }
			if(!empty($gt_apeSociete)){ $sql .= " AND apeSociete > '".$gt_apeSociete."'" ; }
			if(!empty($noapeSociete)){ $sql .= " AND apeSociete ".sqlNotSearch($noapeSociete) ; }
			if(!empty($tvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlSearch($tvaIntraSociete,"tvaIntraSociete") ; }
			if(!empty($lt_tvaIntraSociete)){ $sql .= " AND tvaIntraSociete < '".$lt_tvaIntraSociete."'" ; }
			if(!empty($gt_tvaIntraSociete)){ $sql .= " AND tvaIntraSociete > '".$gt_tvaIntraSociete."'" ; }
			if(!empty($notvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlNotSearch($notvaIntraSociete) ; }
			if(!empty($formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlSearch($formeJuridiqueSociete,"formeJuridiqueSociete") ; }
			if(!empty($lt_formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete < '".$lt_formeJuridiqueSociete."'" ; }
			if(!empty($gt_formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete > '".$gt_formeJuridiqueSociete."'" ; }
			if(!empty($noformeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlNotSearch($noformeJuridiqueSociete) ; }
			if(!empty($capitalSociete)){ $sql .= " AND capitalSociete ".sqlSearch($capitalSociete,"capitalSociete") ; }
			if(!empty($lt_capitalSociete)){ $sql .= " AND capitalSociete < '".$lt_capitalSociete."'" ; }
			if(!empty($gt_capitalSociete)){ $sql .= " AND capitalSociete > '".$gt_capitalSociete."'" ; }
			if(!empty($nocapitalSociete)){ $sql .= " AND capitalSociete ".sqlNotSearch($nocapitalSociete) ; }
			if(!empty($deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlSearch($deviseCapitalSociete,"deviseCapitalSociete") ; }
			if(!empty($lt_deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete < '".$lt_deviseCapitalSociete."'" ; }
			if(!empty($gt_deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete > '".$gt_deviseCapitalSociete."'" ; }
			if(!empty($nodeviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlNotSearch($nodeviseCapitalSociete) ; }
			if(!empty($deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlSearch($deviseFacturationSociete,"deviseFacturationSociete") ; }
			if(!empty($lt_deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete < '".$lt_deviseFacturationSociete."'" ; }
			if(!empty($gt_deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete > '".$gt_deviseFacturationSociete."'" ; }
			if(!empty($nodeviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlNotSearch($nodeviseFacturationSociete) ; }
			if(!empty($activiteSociete)){ $sql .= " AND activiteSociete ".sqlSearch($activiteSociete,"activiteSociete") ; }
			if(!empty($lt_activiteSociete)){ $sql .= " AND activiteSociete < '".$lt_activiteSociete."'" ; }
			if(!empty($gt_activiteSociete)){ $sql .= " AND activiteSociete > '".$gt_activiteSociete."'" ; }
			if(!empty($noactiviteSociete)){ $sql .= " AND activiteSociete ".sqlNotSearch($noactiviteSociete) ; }
			if(!empty($chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlSearch($chiffreAffaireSociete,"chiffreAffaireSociete") ; }
			if(!empty($lt_chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete < '".$lt_chiffreAffaireSociete."'" ; }
			if(!empty($gt_chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete > '".$gt_chiffreAffaireSociete."'" ; }
			if(!empty($nochiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlNotSearch($nochiffreAffaireSociete) ; }
			if(!empty($nbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlSearch($nbSalarieSociete,"nbSalarieSociete") ; }
			if(!empty($lt_nbSalarieSociete)){ $sql .= " AND nbSalarieSociete < '".$lt_nbSalarieSociete."'" ; }
			if(!empty($gt_nbSalarieSociete)){ $sql .= " AND nbSalarieSociete > '".$gt_nbSalarieSociete."'" ; }
			if(!empty($nonbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlNotSearch($nonbSalarieSociete) ; }
			if(!empty($beneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlSearch($beneficeSocitete,"beneficeSocitete") ; }
			if(!empty($lt_beneficeSocitete)){ $sql .= " AND beneficeSocitete < '".$lt_beneficeSocitete."'" ; }
			if(!empty($gt_beneficeSocitete)){ $sql .= " AND beneficeSocitete > '".$gt_beneficeSocitete."'" ; }
			if(!empty($nobeneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlNotSearch($nobeneficeSocitete) ; }
			if(!empty($estFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlSearch($estFacturableSociete,"estFacturableSociete") ; }
			if(!empty($lt_estFacturableSociete)){ $sql .= " AND estFacturableSociete < '".$lt_estFacturableSociete."'" ; }
			if(!empty($gt_estFacturableSociete)){ $sql .= " AND estFacturableSociete > '".$gt_estFacturableSociete."'" ; }
			if(!empty($noestFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlNotSearch($noestFacturableSociete) ; }
			if(!empty($idclient)){ $sql .= " AND idclient ".sqlSearch($idclient,"idclient") ; }
			if(!empty($lt_idclient)){ $sql .= " AND idclient < '".$lt_idclient."'" ; }
			if(!empty($gt_idclient)){ $sql .= " AND idclient > '".$gt_idclient."'" ; }
			if(!empty($noidclient)){ $sql .= " AND idclient ".sqlNotSearch($noidclient) ; }
			if(!empty($societe_idsociete)){ $sql .= " AND societe_idsociete ".sqlSearch($societe_idsociete,"societe_idsociete") ; }
			if(!empty($lt_societe_idsociete)){ $sql .= " AND societe_idsociete < '".$lt_societe_idsociete."'" ; }
			if(!empty($gt_societe_idsociete)){ $sql .= " AND societe_idsociete > '".$gt_societe_idsociete."'" ; }
			if(!empty($nosociete_idsociete)){ $sql .= " AND societe_idsociete ".sqlNotSearch($nosociete_idsociete) ; }
			if(!empty($nomType_location_client)){ $sql .= " AND nomType_location_client ".sqlSearch($nomType_location_client,"nomType_location_client") ; }
			if(!empty($lt_nomType_location_client)){ $sql .= " AND nomType_location_client < '".$lt_nomType_location_client."'" ; }
			if(!empty($gt_nomType_location_client)){ $sql .= " AND nomType_location_client > '".$gt_nomType_location_client."'" ; }
			if(!empty($nonomType_location_client)){ $sql .= " AND nomType_location_client ".sqlNotSearch($nonomType_location_client) ; }
			if(!empty($idtype_location_client)){ $sql .= " AND idtype_location_client ".sqlSearch($idtype_location_client,"idtype_location_client") ; }
			if(!empty($lt_idtype_location_client)){ $sql .= " AND idtype_location_client < '".$lt_idtype_location_client."'" ; }
			if(!empty($gt_idtype_location_client)){ $sql .= " AND idtype_location_client > '".$gt_idtype_location_client."'" ; }
			if(!empty($noidtype_location_client)){ $sql .= " AND idtype_location_client ".sqlNotSearch($noidtype_location_client) ; }
			if(!empty($numContrat)){ $sql .= " AND numContrat ".sqlSearch($numContrat,"numContrat") ; }
			if(!empty($lt_numContrat)){ $sql .= " AND numContrat < '".$lt_numContrat."'" ; }
			if(!empty($gt_numContrat)){ $sql .= " AND numContrat > '".$gt_numContrat."'" ; }
			if(!empty($nonumContrat)){ $sql .= " AND numContrat ".sqlNotSearch($nonumContrat) ; }
			if(!empty($dureeContrat)){ $sql .= " AND dureeContrat ".sqlSearch($dureeContrat,"dureeContrat") ; }
			if(!empty($lt_dureeContrat)){ $sql .= " AND dureeContrat < '".$lt_dureeContrat."'" ; }
			if(!empty($gt_dureeContrat)){ $sql .= " AND dureeContrat > '".$gt_dureeContrat."'" ; }
			if(!empty($nodureeContrat)){ $sql .= " AND dureeContrat ".sqlNotSearch($nodureeContrat) ; }
			if(!empty($dateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlSearch($dateDebutContrat,"dateDebutContrat") ; }
			if(!empty($lt_dateDebutContrat)){ $sql .= " AND dateDebutContrat < '".$lt_dateDebutContrat."'" ; }
			if(!empty($gt_dateDebutContrat)){ $sql .= " AND dateDebutContrat > '".$gt_dateDebutContrat."'" ; }
			if(!empty($nodateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlNotSearch($nodateDebutContrat) ; }
			if(!empty($type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlSearch($type_contrat_idtype_contrat,"type_contrat_idtype_contrat") ; }
			if(!empty($lt_type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat < '".$lt_type_contrat_idtype_contrat."'" ; }
			if(!empty($gt_type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat > '".$gt_type_contrat_idtype_contrat."'" ; }
			if(!empty($notype_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlNotSearch($notype_contrat_idtype_contrat) ; }
			if(!empty($adresse1)){ $sql .= " AND adresse1 ".sqlSearch($adresse1,"adresse1") ; }
			if(!empty($lt_adresse1)){ $sql .= " AND adresse1 < '".$lt_adresse1."'" ; }
			if(!empty($gt_adresse1)){ $sql .= " AND adresse1 > '".$gt_adresse1."'" ; }
			if(!empty($noadresse1)){ $sql .= " AND adresse1 ".sqlNotSearch($noadresse1) ; }
			if(!empty($adresse2)){ $sql .= " AND adresse2 ".sqlSearch($adresse2,"adresse2") ; }
			if(!empty($lt_adresse2)){ $sql .= " AND adresse2 < '".$lt_adresse2."'" ; }
			if(!empty($gt_adresse2)){ $sql .= " AND adresse2 > '".$gt_adresse2."'" ; }
			if(!empty($noadresse2)){ $sql .= " AND adresse2 ".sqlNotSearch($noadresse2) ; }
			if(!empty($codePostalAdresse)){ $sql .= " AND codePostalAdresse ".sqlSearch($codePostalAdresse,"codePostalAdresse") ; }
			if(!empty($lt_codePostalAdresse)){ $sql .= " AND codePostalAdresse < '".$lt_codePostalAdresse."'" ; }
			if(!empty($gt_codePostalAdresse)){ $sql .= " AND codePostalAdresse > '".$gt_codePostalAdresse."'" ; }
			if(!empty($nocodePostalAdresse)){ $sql .= " AND codePostalAdresse ".sqlNotSearch($nocodePostalAdresse) ; }
			if(!empty($villeAdresse)){ $sql .= " AND villeAdresse ".sqlSearch($villeAdresse,"villeAdresse") ; }
			if(!empty($lt_villeAdresse)){ $sql .= " AND villeAdresse < '".$lt_villeAdresse."'" ; }
			if(!empty($gt_villeAdresse)){ $sql .= " AND villeAdresse > '".$gt_villeAdresse."'" ; }
			if(!empty($novilleAdresse)){ $sql .= " AND villeAdresse ".sqlNotSearch($novilleAdresse) ; }
			if(!empty($contrat_idcontrat)){ $sql .= " AND contrat_idcontrat ".sqlSearch($contrat_idcontrat,"contrat_idcontrat") ; }
			if(!empty($lt_contrat_idcontrat)){ $sql .= " AND contrat_idcontrat < '".$lt_contrat_idcontrat."'" ; }
			if(!empty($gt_contrat_idcontrat)){ $sql .= " AND contrat_idcontrat > '".$gt_contrat_idcontrat."'" ; }
			if(!empty($nocontrat_idcontrat)){ $sql .= " AND contrat_idcontrat ".sqlNotSearch($nocontrat_idcontrat) ; }
			
			if(!empty($agent_idagent)){ $sql .= " AND agent_idagent ".sqlSearch($agent_idagent) ; }
			if(!empty($noagent_idagent)){ $sql .= " AND agent_idagent ".sqlNotSearch($noagent_idagent) ; }
			
			if(!empty($groupBy)){ $sql .= " group by $groupBy";  }
			if(!empty($orderBy)){ $sql .= " order by $orderBy";  }
			if(!empty($debug)){ echo $sql;   }
			if(!empty($nbRows) && !empty($page) ){ return $this->conn ->PageExecute($sql,$nbRows,$page);}
	return $this->conn->Execute($sql) ;	
	}
	function getAllSearchLocationClient(){ 
		$sql="SELECT * FROM  vue_search_location_client"; 
		return $this->conn->Execute($sql) ;	
	}
	function getSelectOneSearchLocationClient($name="idvue_search_location_client",$id="",$allowEmpty= false,$params)
	{ 
		extract($params,EXTR_OVERWRITE) ;	
		$sql = "SELECT nomVue_search_location_client , idvue_search_location_client FROM vue_search_location_client WHERE  1 ";  
			if(!empty($idlocation_client)){ $sql .= " AND idlocation_client ".sqlIn($idlocation_client) ; }
			if(!empty($gt_idlocation_client)){ $sql .= " AND idlocation_client > ".$gt_idlocation_client ; }
			if(!empty($noidlocation_client)){ $sql .= " AND idlocation_client ".sqlNotIn($noidlocation_client) ; }
			if(!empty($type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlIn($type_location_client_idtype_location_client) ; }
			if(!empty($gt_type_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client > ".$gt_type_location_client_idtype_location_client ; }
			if(!empty($notype_location_client_idtype_location_client)){ $sql .= " AND type_location_client_idtype_location_client ".sqlNotIn($notype_location_client_idtype_location_client) ; }
			if(!empty($client_idclient)){ $sql .= " AND client_idclient ".sqlIn($client_idclient) ; }
			if(!empty($gt_client_idclient)){ $sql .= " AND client_idclient > ".$gt_client_idclient ; }
			if(!empty($noclient_idclient)){ $sql .= " AND client_idclient ".sqlNotIn($noclient_idclient) ; }
			if(!empty($numeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlIn($numeroLocation_client) ; }
			if(!empty($gt_numeroLocation_client)){ $sql .= " AND numeroLocation_client > ".$gt_numeroLocation_client ; }
			if(!empty($nonumeroLocation_client)){ $sql .= " AND numeroLocation_client ".sqlNotIn($nonumeroLocation_client) ; }
			if(!empty($dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlIn($dateCreationLocation_client) ; }
			if(!empty($gt_dateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client > ".$gt_dateCreationLocation_client ; }
			if(!empty($nodateCreationLocation_client)){ $sql .= " AND dateCreationLocation_client ".sqlNotIn($nodateCreationLocation_client) ; }
			if(!empty($dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlIn($dateDebutLocation_client) ; }
			if(!empty($gt_dateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client > ".$gt_dateDebutLocation_client ; }
			if(!empty($nodateDebutLocation_client)){ $sql .= " AND dateDebutLocation_client ".sqlNotIn($nodateDebutLocation_client) ; }
			if(!empty($dateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlIn($dateFinLocation_client) ; }
			if(!empty($gt_dateFinLocation_client)){ $sql .= " AND dateFinLocation_client > ".$gt_dateFinLocation_client ; }
			if(!empty($nodateFinLocation_client)){ $sql .= " AND dateFinLocation_client ".sqlNotIn($nodateFinLocation_client) ; }
			if(!empty($dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlIn($dateClotureLocation_client) ; }
			if(!empty($gt_dateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client > ".$gt_dateClotureLocation_client ; }
			if(!empty($nodateClotureLocation_client)){ $sql .= " AND dateClotureLocation_client ".sqlNotIn($nodateClotureLocation_client) ; }
			if(!empty($idligne_location_client)){ $sql .= " AND idligne_location_client ".sqlIn($idligne_location_client) ; }
			if(!empty($gt_idligne_location_client)){ $sql .= " AND idligne_location_client > ".$gt_idligne_location_client ; }
			if(!empty($noidligne_location_client)){ $sql .= " AND idligne_location_client ".sqlNotIn($noidligne_location_client) ; }
			if(!empty($localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlIn($localisation_idlocalisation) ; }
			if(!empty($gt_localisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation > ".$gt_localisation_idlocalisation ; }
			if(!empty($nolocalisation_idlocalisation)){ $sql .= " AND localisation_idlocalisation ".sqlNotIn($nolocalisation_idlocalisation) ; }
			if(!empty($materiel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlIn($materiel_idmateriel) ; }
			if(!empty($gt_materiel_idmateriel)){ $sql .= " AND materiel_idmateriel > ".$gt_materiel_idmateriel ; }
			if(!empty($nomateriel_idmateriel)){ $sql .= " AND materiel_idmateriel ".sqlNotIn($nomateriel_idmateriel) ; }
			if(!empty($location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlIn($location_client_idlocation_client) ; }
			if(!empty($gt_location_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client > ".$gt_location_client_idlocation_client ; }
			if(!empty($nolocation_client_idlocation_client)){ $sql .= " AND location_client_idlocation_client ".sqlNotIn($nolocation_client_idlocation_client) ; }
			if(!empty($dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlIn($dateCreationLigne_location_client) ; }
			if(!empty($gt_dateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client > ".$gt_dateCreationLigne_location_client ; }
			if(!empty($nodateCreationLigne_location_client)){ $sql .= " AND dateCreationLigne_location_client ".sqlNotIn($nodateCreationLigne_location_client) ; }
			if(!empty($dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlIn($dateDebutLigne_location_client) ; }
			if(!empty($gt_dateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client > ".$gt_dateDebutLigne_location_client ; }
			if(!empty($nodateDebutLigne_location_client)){ $sql .= " AND dateDebutLigne_location_client ".sqlNotIn($nodateDebutLigne_location_client) ; }
			if(!empty($dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlIn($dateClotureLigne_location_client) ; }
			if(!empty($gt_dateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client > ".$gt_dateClotureLigne_location_client ; }
			if(!empty($nodateClotureLigne_location_client)){ $sql .= " AND dateClotureLigne_location_client ".sqlNotIn($nodateClotureLigne_location_client) ; }
			if(!empty($dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlIn($dateFinLigne_location_client) ; }
			if(!empty($gt_dateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client > ".$gt_dateFinLigne_location_client ; }
			if(!empty($nodateFinLigne_location_client)){ $sql .= " AND dateFinLigne_location_client ".sqlNotIn($nodateFinLigne_location_client) ; }
			if(!empty($dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlIn($dureeLigne_location_client) ; }
			if(!empty($gt_dureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client > ".$gt_dureeLigne_location_client ; }
			if(!empty($nodureeLigne_location_client)){ $sql .= " AND dureeLigne_location_client ".sqlNotIn($nodureeLigne_location_client) ; }
			if(!empty($uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlIn($uniteDureeLigne_location_client) ; }
			if(!empty($gt_uniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client > ".$gt_uniteDureeLigne_location_client ; }
			if(!empty($nouniteDureeLigne_location_client)){ $sql .= " AND uniteDureeLigne_location_client ".sqlNotIn($nouniteDureeLigne_location_client) ; }
			if(!empty($pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlIn($pvhtLigne_location_client) ; }
			if(!empty($gt_pvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client > ".$gt_pvhtLigne_location_client ; }
			if(!empty($nopvhtLigne_location_client)){ $sql .= " AND pvhtLigne_location_client ".sqlNotIn($nopvhtLigne_location_client) ; }
			if(!empty($idproduit)){ $sql .= " AND idproduit ".sqlIn($idproduit) ; }
			if(!empty($gt_idproduit)){ $sql .= " AND idproduit > ".$gt_idproduit ; }
			if(!empty($noidproduit)){ $sql .= " AND idproduit ".sqlNotIn($noidproduit) ; }
			if(!empty($gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlIn($gamme_produit_idgamme_produit) ; }
			if(!empty($gt_gamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit > ".$gt_gamme_produit_idgamme_produit ; }
			if(!empty($nogamme_produit_idgamme_produit)){ $sql .= " AND gamme_produit_idgamme_produit ".sqlNotIn($nogamme_produit_idgamme_produit) ; }
			if(!empty($marque_idmarque)){ $sql .= " AND marque_idmarque ".sqlIn($marque_idmarque) ; }
			if(!empty($gt_marque_idmarque)){ $sql .= " AND marque_idmarque > ".$gt_marque_idmarque ; }
			if(!empty($nomarque_idmarque)){ $sql .= " AND marque_idmarque ".sqlNotIn($nomarque_idmarque) ; }
			if(!empty($referenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlIn($referenceInterneProduit) ; }
			if(!empty($gt_referenceInterneProduit)){ $sql .= " AND referenceInterneProduit > ".$gt_referenceInterneProduit ; }
			if(!empty($noreferenceInterneProduit)){ $sql .= " AND referenceInterneProduit ".sqlNotIn($noreferenceInterneProduit) ; }
			if(!empty($nomProduit)){ $sql .= " AND nomProduit ".sqlIn($nomProduit) ; }
			if(!empty($gt_nomProduit)){ $sql .= " AND nomProduit > ".$gt_nomProduit ; }
			if(!empty($nonomProduit)){ $sql .= " AND nomProduit ".sqlNotIn($nonomProduit) ; }
			if(!empty($pahtProduit)){ $sql .= " AND pahtProduit ".sqlIn($pahtProduit) ; }
			if(!empty($gt_pahtProduit)){ $sql .= " AND pahtProduit > ".$gt_pahtProduit ; }
			if(!empty($nopahtProduit)){ $sql .= " AND pahtProduit ".sqlNotIn($nopahtProduit) ; }
			if(!empty($pvhtProduit)){ $sql .= " AND pvhtProduit ".sqlIn($pvhtProduit) ; }
			if(!empty($gt_pvhtProduit)){ $sql .= " AND pvhtProduit > ".$gt_pvhtProduit ; }
			if(!empty($nopvhtProduit)){ $sql .= " AND pvhtProduit ".sqlNotIn($nopvhtProduit) ; }
			if(!empty($commentaireProduit)){ $sql .= " AND commentaireProduit ".sqlIn($commentaireProduit) ; }
			if(!empty($gt_commentaireProduit)){ $sql .= " AND commentaireProduit > ".$gt_commentaireProduit ; }
			if(!empty($nocommentaireProduit)){ $sql .= " AND commentaireProduit ".sqlNotIn($nocommentaireProduit) ; }
			if(!empty($estActifProduit)){ $sql .= " AND estActifProduit ".sqlIn($estActifProduit) ; }
			if(!empty($gt_estActifProduit)){ $sql .= " AND estActifProduit > ".$gt_estActifProduit ; }
			if(!empty($noestActifProduit)){ $sql .= " AND estActifProduit ".sqlNotIn($noestActifProduit) ; }
			if(!empty($qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlIn($qteAlerteStockProduit) ; }
			if(!empty($gt_qteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit > ".$gt_qteAlerteStockProduit ; }
			if(!empty($noqteAlerteStockProduit)){ $sql .= " AND qteAlerteStockProduit ".sqlNotIn($noqteAlerteStockProduit) ; }
			if(!empty($idmateriel)){ $sql .= " AND idmateriel ".sqlIn($idmateriel) ; }
			if(!empty($gt_idmateriel)){ $sql .= " AND idmateriel > ".$gt_idmateriel ; }
			if(!empty($noidmateriel)){ $sql .= " AND idmateriel ".sqlNotIn($noidmateriel) ; }
			if(!empty($stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlIn($stock_materiel_idstock_materiel) ; }
			if(!empty($gt_stock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel > ".$gt_stock_materiel_idstock_materiel ; }
			if(!empty($nostock_materiel_idstock_materiel)){ $sql .= " AND stock_materiel_idstock_materiel ".sqlNotIn($nostock_materiel_idstock_materiel) ; }
			if(!empty($produit_idproduit)){ $sql .= " AND produit_idproduit ".sqlIn($produit_idproduit) ; }
			if(!empty($gt_produit_idproduit)){ $sql .= " AND produit_idproduit > ".$gt_produit_idproduit ; }
			if(!empty($noproduit_idproduit)){ $sql .= " AND produit_idproduit ".sqlNotIn($noproduit_idproduit) ; }
			if(!empty($numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlIn($numeroSerieInterneMateriel) ; }
			if(!empty($gt_numeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel > ".$gt_numeroSerieInterneMateriel ; }
			if(!empty($nonumeroSerieInterneMateriel)){ $sql .= " AND numeroSerieInterneMateriel ".sqlNotIn($nonumeroSerieInterneMateriel) ; }
			if(!empty($numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlIn($numeroSerieExterneMateriel) ; }
			if(!empty($gt_numeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel > ".$gt_numeroSerieExterneMateriel ; }
			if(!empty($nonumeroSerieExterneMateriel)){ $sql .= " AND numeroSerieExterneMateriel ".sqlNotIn($nonumeroSerieExterneMateriel) ; }
			if(!empty($dateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlIn($dateCreationMateriel) ; }
			if(!empty($gt_dateCreationMateriel)){ $sql .= " AND dateCreationMateriel > ".$gt_dateCreationMateriel ; }
			if(!empty($nodateCreationMateriel)){ $sql .= " AND dateCreationMateriel ".sqlNotIn($nodateCreationMateriel) ; }
			if(!empty($dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlIn($dateAcquisitionMateriel) ; }
			if(!empty($gt_dateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel > ".$gt_dateAcquisitionMateriel ; }
			if(!empty($nodateAcquisitionMateriel)){ $sql .= " AND dateAcquisitionMateriel ".sqlNotIn($nodateAcquisitionMateriel) ; }
			if(!empty($dateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlIn($dateFinMateriel) ; }
			if(!empty($gt_dateFinMateriel)){ $sql .= " AND dateFinMateriel > ".$gt_dateFinMateriel ; }
			if(!empty($nodateFinMateriel)){ $sql .= " AND dateFinMateriel ".sqlNotIn($nodateFinMateriel) ; }
			if(!empty($estActifMateriel)){ $sql .= " AND estActifMateriel ".sqlIn($estActifMateriel) ; }
			if(!empty($gt_estActifMateriel)){ $sql .= " AND estActifMateriel > ".$gt_estActifMateriel ; }
			if(!empty($noestActifMateriel)){ $sql .= " AND estActifMateriel ".sqlNotIn($noestActifMateriel) ; }
			if(!empty($pahtMateriel)){ $sql .= " AND pahtMateriel ".sqlIn($pahtMateriel) ; }
			if(!empty($gt_pahtMateriel)){ $sql .= " AND pahtMateriel > ".$gt_pahtMateriel ; }
			if(!empty($nopahtMateriel)){ $sql .= " AND pahtMateriel ".sqlNotIn($nopahtMateriel) ; }
			if(!empty($pvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlIn($pvhtMateriel) ; }
			if(!empty($gt_pvhtMateriel)){ $sql .= " AND pvhtMateriel > ".$gt_pvhtMateriel ; }
			if(!empty($nopvhtMateriel)){ $sql .= " AND pvhtMateriel ".sqlNotIn($nopvhtMateriel) ; }
			if(!empty($commentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlIn($commentaireMateriel) ; }
			if(!empty($gt_commentaireMateriel)){ $sql .= " AND commentaireMateriel > ".$gt_commentaireMateriel ; }
			if(!empty($nocommentaireMateriel)){ $sql .= " AND commentaireMateriel ".sqlNotIn($nocommentaireMateriel) ; }
			if(!empty($idsociete)){ $sql .= " AND idsociete ".sqlIn($idsociete) ; }
			if(!empty($gt_idsociete)){ $sql .= " AND idsociete > ".$gt_idsociete ; }
			if(!empty($noidsociete)){ $sql .= " AND idsociete ".sqlNotIn($noidsociete) ; }
			if(!empty($nomSociete)){ $sql .= " AND nomSociete ".sqlIn($nomSociete) ; }
			if(!empty($gt_nomSociete)){ $sql .= " AND nomSociete > ".$gt_nomSociete ; }
			if(!empty($nonomSociete)){ $sql .= " AND nomSociete ".sqlNotIn($nonomSociete) ; }
			if(!empty($siretSociete)){ $sql .= " AND siretSociete ".sqlIn($siretSociete) ; }
			if(!empty($gt_siretSociete)){ $sql .= " AND siretSociete > ".$gt_siretSociete ; }
			if(!empty($nosiretSociete)){ $sql .= " AND siretSociete ".sqlNotIn($nosiretSociete) ; }
			if(!empty($sirenSociete)){ $sql .= " AND sirenSociete ".sqlIn($sirenSociete) ; }
			if(!empty($gt_sirenSociete)){ $sql .= " AND sirenSociete > ".$gt_sirenSociete ; }
			if(!empty($nosirenSociete)){ $sql .= " AND sirenSociete ".sqlNotIn($nosirenSociete) ; }
			if(!empty($apeSociete)){ $sql .= " AND apeSociete ".sqlIn($apeSociete) ; }
			if(!empty($gt_apeSociete)){ $sql .= " AND apeSociete > ".$gt_apeSociete ; }
			if(!empty($noapeSociete)){ $sql .= " AND apeSociete ".sqlNotIn($noapeSociete) ; }
			if(!empty($tvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlIn($tvaIntraSociete) ; }
			if(!empty($gt_tvaIntraSociete)){ $sql .= " AND tvaIntraSociete > ".$gt_tvaIntraSociete ; }
			if(!empty($notvaIntraSociete)){ $sql .= " AND tvaIntraSociete ".sqlNotIn($notvaIntraSociete) ; }
			if(!empty($formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlIn($formeJuridiqueSociete) ; }
			if(!empty($gt_formeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete > ".$gt_formeJuridiqueSociete ; }
			if(!empty($noformeJuridiqueSociete)){ $sql .= " AND formeJuridiqueSociete ".sqlNotIn($noformeJuridiqueSociete) ; }
			if(!empty($capitalSociete)){ $sql .= " AND capitalSociete ".sqlIn($capitalSociete) ; }
			if(!empty($gt_capitalSociete)){ $sql .= " AND capitalSociete > ".$gt_capitalSociete ; }
			if(!empty($nocapitalSociete)){ $sql .= " AND capitalSociete ".sqlNotIn($nocapitalSociete) ; }
			if(!empty($deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlIn($deviseCapitalSociete) ; }
			if(!empty($gt_deviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete > ".$gt_deviseCapitalSociete ; }
			if(!empty($nodeviseCapitalSociete)){ $sql .= " AND deviseCapitalSociete ".sqlNotIn($nodeviseCapitalSociete) ; }
			if(!empty($deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlIn($deviseFacturationSociete) ; }
			if(!empty($gt_deviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete > ".$gt_deviseFacturationSociete ; }
			if(!empty($nodeviseFacturationSociete)){ $sql .= " AND deviseFacturationSociete ".sqlNotIn($nodeviseFacturationSociete) ; }
			if(!empty($activiteSociete)){ $sql .= " AND activiteSociete ".sqlIn($activiteSociete) ; }
			if(!empty($gt_activiteSociete)){ $sql .= " AND activiteSociete > ".$gt_activiteSociete ; }
			if(!empty($noactiviteSociete)){ $sql .= " AND activiteSociete ".sqlNotIn($noactiviteSociete) ; }
			if(!empty($chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlIn($chiffreAffaireSociete) ; }
			if(!empty($gt_chiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete > ".$gt_chiffreAffaireSociete ; }
			if(!empty($nochiffreAffaireSociete)){ $sql .= " AND chiffreAffaireSociete ".sqlNotIn($nochiffreAffaireSociete) ; }
			if(!empty($nbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlIn($nbSalarieSociete) ; }
			if(!empty($gt_nbSalarieSociete)){ $sql .= " AND nbSalarieSociete > ".$gt_nbSalarieSociete ; }
			if(!empty($nonbSalarieSociete)){ $sql .= " AND nbSalarieSociete ".sqlNotIn($nonbSalarieSociete) ; }
			if(!empty($beneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlIn($beneficeSocitete) ; }
			if(!empty($gt_beneficeSocitete)){ $sql .= " AND beneficeSocitete > ".$gt_beneficeSocitete ; }
			if(!empty($nobeneficeSocitete)){ $sql .= " AND beneficeSocitete ".sqlNotIn($nobeneficeSocitete) ; }
			if(!empty($estFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlIn($estFacturableSociete) ; }
			if(!empty($gt_estFacturableSociete)){ $sql .= " AND estFacturableSociete > ".$gt_estFacturableSociete ; }
			if(!empty($noestFacturableSociete)){ $sql .= " AND estFacturableSociete ".sqlNotIn($noestFacturableSociete) ; }
			if(!empty($idclient)){ $sql .= " AND idclient ".sqlIn($idclient) ; }
			if(!empty($gt_idclient)){ $sql .= " AND idclient > ".$gt_idclient ; }
			if(!empty($noidclient)){ $sql .= " AND idclient ".sqlNotIn($noidclient) ; }
			if(!empty($societe_idsociete)){ $sql .= " AND societe_idsociete ".sqlIn($societe_idsociete) ; }
			if(!empty($gt_societe_idsociete)){ $sql .= " AND societe_idsociete > ".$gt_societe_idsociete ; }
			if(!empty($nosociete_idsociete)){ $sql .= " AND societe_idsociete ".sqlNotIn($nosociete_idsociete) ; }
			if(!empty($nomType_location_client)){ $sql .= " AND nomType_location_client ".sqlIn($nomType_location_client) ; }
			if(!empty($gt_nomType_location_client)){ $sql .= " AND nomType_location_client > ".$gt_nomType_location_client ; }
			if(!empty($nonomType_location_client)){ $sql .= " AND nomType_location_client ".sqlNotIn($nonomType_location_client) ; }
			if(!empty($idtype_location_client)){ $sql .= " AND idtype_location_client ".sqlIn($idtype_location_client) ; }
			if(!empty($gt_idtype_location_client)){ $sql .= " AND idtype_location_client > ".$gt_idtype_location_client ; }
			if(!empty($noidtype_location_client)){ $sql .= " AND idtype_location_client ".sqlNotIn($noidtype_location_client) ; }
			if(!empty($numContrat)){ $sql .= " AND numContrat ".sqlIn($numContrat) ; }
			if(!empty($gt_numContrat)){ $sql .= " AND numContrat > ".$gt_numContrat ; }
			if(!empty($nonumContrat)){ $sql .= " AND numContrat ".sqlNotIn($nonumContrat) ; }
			if(!empty($dureeContrat)){ $sql .= " AND dureeContrat ".sqlIn($dureeContrat) ; }
			if(!empty($gt_dureeContrat)){ $sql .= " AND dureeContrat > ".$gt_dureeContrat ; }
			if(!empty($nodureeContrat)){ $sql .= " AND dureeContrat ".sqlNotIn($nodureeContrat) ; }
			if(!empty($dateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlIn($dateDebutContrat) ; }
			if(!empty($gt_dateDebutContrat)){ $sql .= " AND dateDebutContrat > ".$gt_dateDebutContrat ; }
			if(!empty($nodateDebutContrat)){ $sql .= " AND dateDebutContrat ".sqlNotIn($nodateDebutContrat) ; }
			if(!empty($type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlIn($type_contrat_idtype_contrat) ; }
			if(!empty($gt_type_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat > ".$gt_type_contrat_idtype_contrat ; }
			if(!empty($notype_contrat_idtype_contrat)){ $sql .= " AND type_contrat_idtype_contrat ".sqlNotIn($notype_contrat_idtype_contrat) ; }
			if(!empty($groupBy)){ $sql .= " group by $groupBy " ; } 
		$sql .=" ORDER BY nomVue_search_location_client ";
		$rs = $this->conn->Execute($sql) ; 
		return $rs->GetMenu2($name,$id,$allowEmpty); 
	}
	function getSelectSearchLocationClient($name="idvue_search_location_client",$id="",$allowEmpty= false)
	{ 
		$sql = "SELECT nomVue_search_location_client , idvue_search_location_client FROM vue_search_location_client ORDER BY nomVue_search_location_client ";
		$rs = $this->conn->Execute($sql) ; 
		return $rs->GetMenu2($name,$id,$allowEmpty); 
	}
}
$ClassSearchLocationClient = new SearchLocationClient(); ?>